version: '3.7'

services:
  database:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    ports:
      - "5432:5432"
    volumes:
      - database-pg:/var/lib/postgresql/data

volumes:
  database-pg:
